from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class AtlasFrontendTests(unittest.TestCase):
    def setUp(self):
        self.app = (ROOT / "site/app.js").read_text(encoding="utf-8")
        self.styles = (ROOT / "site/styles.css").read_text(encoding="utf-8")
        self.english = (ROOT / "site/index.html").read_text(encoding="utf-8")
        self.chinese = (ROOT / "site/zh-CN.html").read_text(encoding="utf-8")

    def test_both_languages_expose_shareable_result_controls(self):
        for page in (self.english, self.chinese):
            self.assertIn('id="copy-link"', page)
            self.assertIn('id="copy-status"', page)
            self.assertIn("<noscript>", page)
            self.assertIn("catalog.json", page)
            self.assertIn('id="language-link"', page)
            self.assertIn('id="snapshot-note"', page)
            self.assertIn('id="curated-note"', page)
            self.assertIn('id="curated-count-text"', page)
            self.assertIn("?packageStatus=reviewed#catalog", page)
            self.assertIn('id="hero-count"', page)
            self.assertIn('id="search"', page)
            self.assertIn('class="keyboard-hint"', page)
            self.assertIn("Esc", page)
            self.assertIn('class="skip-link"', page)
            self.assertIn('href="#catalog"', page)
            self.assertIn('id="package-status"', page)
            self.assertIn('class="search-example"', page)
            self.assertIn("data-search=", page)
            self.assertIn("catalog-action-note", page)
            self.assertIn("Star", page)
            self.assertIn("disabled", page)
            self.assertIn('aria-live="polite"', page)
            self.assertIn('id="external-search"', page)
            self.assertIn('id="empty-reset"', page)
            self.assertIn('id="retry-load"', page)
            self.assertIn("feature.yml", page)
            if page is self.english:
                self.assertIn("Request a capability", page)
                self.assertIn("Retry loading", page)
            else:
                self.assertIn("提交能力需求", page)
                self.assertIn("重试加载", page)
            self.assertIn("filename%3ASKILL.md", page)
            self.assertIn("/discussions", page)
            self.assertIn("sandbaseai/awesome-workbuddy", page)
            self.assertIn("docs/resources", page)
            self.assertIn("docs/starter-packs", page)
            self.assertIn("docs/quickstart", page)
            self.assertIn("/tree/main/catalog", page)
            self.assertIn("quickstart", page)
            self.assertIn("catalog-schema.json", page)
            self.assertIn("catalog-meta.json", page)
            self.assertIn("catalog-meta-schema.json", page)
            self.assertIn("packages.json", page)
            self.assertIn("packages.html", page)
            self.assertIn("packages-schema.json", page)
            self.assertIn("package-feedback.yml", page)
            self.assertIn("footer-links", page)
            self.assertIn("SUPPORT.md", page)
            self.assertIn("docs/quickstart", page)
            self.assertIn("docs/resources", page)

    def test_url_state_supports_sharing_and_browser_history(self):
        self.assertIn("new URLSearchParams(location.search)", self.app)
        self.assertIn("copySearchLink", self.app)
        self.assertIn('window.addEventListener("popstate"', self.app)
        self.assertIn('history[`${historyMode}State`]', self.app)
        self.assertIn('search({ historyMode: "push" })', self.app)
        self.assertIn("syncLanguageLink", self.app)
        self.assertIn("function syncExternalSearchLink()", self.app)
        self.assertIn("filename:SKILL.md", self.app)
        self.assertIn("new URLSearchParams({ q: search, type: \"code\" })", self.app)
        self.assertIn("control.value = control.options[0].value", self.app)
        self.assertIn("meta.records.toLocaleString()", self.app)
        self.assertIn("meta.curated_adaptations.toLocaleString()", self.app)
        self.assertIn("heroCount.textContent", self.app)
        self.assertIn("function announceCopy(message)", self.app)
        self.assertIn('return String(value ?? "").replace', self.app)
        self.assertIn('(skill.x || []).join', self.app)
        self.assertIn("async function copyText(value)", self.app)
        self.assertIn('throw new Error("copy failed")', self.app)
        self.assertIn("Could not copy catalog ID", self.app)
        self.assertIn("Could not copy result link", self.app)
        self.assertIn("copyStatus.textContent = message", self.app)
        self.assertIn('event.key === "/"', self.app)
        self.assertIn('event.key === "Escape"', self.app)
        self.assertIn("input.focus()", self.app)
        self.assertIn('search({ historyMode: "push" })', self.app)
        self.assertIn('document.querySelectorAll(".search-example")', self.app)
        self.assertIn('historyMode: "push"', self.app)
        self.assertIn('meta.snapshot_frozen !== true', self.app)
        self.assertIn("async function loadCatalog()", self.app)
        self.assertIn('retryLoad.addEventListener("click", loadCatalog)', self.app)
        self.assertIn('emptyReset.addEventListener("click", () => resetFilters.click())', self.app)
        self.assertIn("retryLoad.disabled = true", self.app)
        self.assertIn("retryLoad.disabled = false", self.app)
        self.assertIn("const compareStable = (left, right) =>", self.app)
        self.assertIn("return a < b ? -1 : a > b ? 1 : 0;", self.app)
        self.assertIn("const bySource = (left, right) => compareStable(left.r, right.r) || compareStable(left.p, right.p);", self.app)
        self.assertIn('} else if (sort.value === "source") {', self.app)
        self.assertIn('const packageStatus = document.querySelector("#package-status")', self.app)
        self.assertIn('packageStatus.value === "reviewed"', self.app)
        self.assertIn('packageStatus.value === "all"', self.app)
        self.assertIn('class="badge package-review"', self.app)
        self.assertIn("reviewed package", self.app)
        self.assertIn("精选包", self.app)
        self.assertIn("个副本", self.app)
        self.assertIn("`${skill.c} copies`", self.app)
        self.assertIn("DEFAULT_CHECKSUM_URL", self.app)
        self.assertIn("meta.release_checksum_url", self.app)
        self.assertIn("校验 SHA256", self.app)
        self.assertIn("Verify SHA256", self.app)
        self.assertIn("result-verify", self.app)
        self.assertIn(".result-verify", self.styles)
        self.assertIn("packageInstallCommand", self.app)
        self.assertIn('fetch("packages.json")', self.app)
        self.assertIn("packagesByDownload", self.app)
        self.assertIn("download_command", self.app)
        self.assertIn("--pattern '", self.app)
        self.assertIn("SHA256SUMS", self.app)
        self.assertIn("--clobber", self.app)
        self.assertIn("copyInstallCommand", self.app)
        self.assertIn("copy-install", self.app)
        self.assertIn("Copy catalog ID for ${escapeHtml(skill.n)}", self.app)
        self.assertIn("Copy install command for ${escapeHtml(skill.n)}", self.app)
        self.assertIn("Download install ZIP for ${escapeHtml(skill.n)}", self.app)
        self.assertIn("Verify SHA256 for ${escapeHtml(skill.n)}", self.app)
        self.assertIn("Inspect source for ${escapeHtml(skill.n)}", self.app)
        self.assertIn("下载 ${escapeHtml(skill.n)} 安装包", self.app)
        self.assertIn("校验 ${escapeHtml(skill.n)} 的 SHA256", self.app)
        self.assertIn("查看 ${escapeHtml(skill.n)} 的来源", self.app)
        self.assertIn("复制 ${escapeHtml(skill.n)} 的目录 ID", self.app)
        self.assertIn("复制 ${escapeHtml(skill.n)} 的安装命令", self.app)
        self.assertIn(".copy-install", self.styles)
        self.assertIn(".badge.package-review", self.styles)
        self.assertIn("curatedCountText.textContent", self.app)
        self.assertIn("${catalogId(skill)}", self.app)
        self.assertIn('<h3 class="result-name">', self.app)
        self.assertIn(".result-name { margin: 0;", self.styles)
        self.assertIn("catalog ID", self.english)
        self.assertIn("目录 ID", self.chinese)

    def test_mobile_navigation_can_wrap(self):
        self.assertIn(".nav { height: auto;", self.styles)
        self.assertIn(".skip-link:focus { top: 0; }", self.styles)
        self.assertIn("flex-wrap: wrap", self.styles)
        self.assertIn("nav { flex: 1 1 100%;", self.styles)

    def test_public_snapshot_note_points_users_to_upstream_sources(self):
        for page in (self.english, self.chinese):
            self.assertIn('class="snapshot-note"', page)
            self.assertNotIn("does not automatically add new catalog records", page)
            self.assertNotIn("不会自动增加新的目录记录", page)
        self.assertIn("Follow each source link for upstream updates.", self.app)
        self.assertIn("请通过来源链接查看上游更新。", self.app)


if __name__ == "__main__":
    unittest.main()
